### ISSUE TITLE
Getting error in Console

### ISSUE THREAD

**Issue by avadheww** [j-catania/ngx-apple-signin#12]
Hii,
Getting this error in console, I have added this meta tag 

Content-Security-Policy"
content="default-src *; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://appleid.apple.com https://appleid.cdn-apple.com "

Refused to execute inline script because it violates the following Content Security Policy directive: "script-src 'self' https://*.apple.com https://*.cdn-apple.com ". Either the 'unsafe-inline' keyword, a hash ('sha256-6wRdeNJzEHNIsDAMAdKbdVLWIqu8b6+Bs+xVNZqplQw='), or a nonce ('nonce-...') is required to enable inline execution.

**Comment by j-catania** [comment]
Hi @avadheww,

Can you please tell me the version you are using ?

**Comment by avadheww** [comment]
I have used ngx-apple-signin@9.0.0

and Project angular version is also 9

**Comment by j-catania** [comment]
Hi @avadheww ,

could you please show me the navigator console and network tabs via screenshot in this feed ?

**Comment by jpike88** [comment]
looks like this plugin should be dynamically importing the apple script...

**Comment by j-catania** [comment]
Hi @jpike88,

This is a feature that I wanted to do.

Can you create a PR for doing this please ?

Thanks,
Juu'
