### ISSUE TITLE
Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by huuquyasb** [j-catania/ngx-apple-signin#8]
Angular 8

![image](https://user-images.githubusercontent.com/20983220/88610948-2ca52d00-d0b2-11ea-86df-a91f46c20c36.png)

**Comment by huuquyasb** [comment]
I think error from appleid.auth.js
I added index.html  it working @@
`<div id="appleid-signin" data-color="black" data-border="true" data-type="sign in" style="display: none;"></div>`
Thanks your project

**Comment by j-catania** [comment]
Hi @huuquyasb,

Glad that you resolve your problem.

Thanks for appreciate the component.

Juu'

**Comment by j-catania** [comment]
@zukicmirzet94, this will maybe help you :)
